language: php

notifications:
    email:
        on_success: never

matrix:
    fast_finish: true
    include:
        -   php: 7.3
            env: dependencies=lowest
        -   php: 7.4
        -   php: 7.4
            env: dependencies=lowest
        -   php: 8.0
        -   php: 8.0
            env: setup=lowest
        -   php: 8.1
        -   php: 8.1
            env: setup=lowest

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install -n
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
    - vendor/bin/phpunit
